[package]
name = "axum_web_server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.7" }
tokio = { version = "1", features = ["full"] }
tower = "0.5.2"
#config = { version = "0.15.9" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0"}
